# Generated by Django 3.1.3 on 2020-11-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201114_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags1',
            new_name='tags',
        ),
    ]
